# Generated by Django 5.0.4 on 2024-05-07 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Не указано', max_length=100, verbose_name='Название кафедры')),
            ],
            options={
                'verbose_name': 'Кафедру',
                'verbose_name_plural': 'Кафедры',
            },
        ),
        migrations.CreateModel(
            name='Specialitys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Не указано', max_length=100, verbose_name='Название специальности')),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
            },
        ),
        migrations.CreateModel(
            name='Universitys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Не указано', max_length=100)),
            ],
            options={
                'verbose_name': 'Университет',
                'verbose_name_plural': 'Университеты',
            },
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Студент'), (1, 'Преподаватель'), (2, 'Бизнес')], verbose_name='Тип учетной записи')),
                ('firstname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('secondname', models.CharField(max_length=100, verbose_name='Имя')),
                ('therename', models.CharField(max_length=100, verbose_name='Отчество')),
                ('avatar', models.ImageField(default=None, null=True, upload_to='avatars', verbose_name='Аватар')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Логин')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='Busineses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_company', models.CharField(max_length=100, verbose_name='Название компании')),
                ('inn_company', models.IntegerField(verbose_name='ИНН компании')),
                ('possition', models.CharField(max_length=100, verbose_name='Должность')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_data', to='profiles.profiles', verbose_name='Логин')),
            ],
            options={
                'verbose_name': 'Бизнес',
                'verbose_name_plural': 'Бизнесы',
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(choices=[(0, 'Лаборант'), (1, 'Ассистент'), (2, 'Старший преподаватель'), (3, 'Доцент'), (4, 'Профессор'), (5, 'Заведующий кафедрой')])),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.departament', verbose_name='Кафедры')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_data', to='profiles.profiles', verbose_name='Логин')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.universitys', verbose_name='Университет')),
            ],
            options={
                'verbose_name': 'Учителя',
                'verbose_name_plural': 'Учителей',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_data', to='profiles.profiles', verbose_name='Логин')),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.specialitys', verbose_name='Специальность')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.universitys', verbose_name='Университет')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.AddField(
            model_name='specialitys',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.universitys', verbose_name='Университет'),
        ),
        migrations.AddField(
            model_name='departament',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.universitys', verbose_name='Университет'),
        ),
    ]
