# Generated by Django 5.0.4 on 2024-05-02 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='type',
            field=models.CharField(choices=[('Студент', 'Студент'), ('Преподаватель', 'Преподаватель'), ('Бизнес', 'Бизнес')], max_length=100),
        ),
        migrations.AddField(
            model_name='specialitys',
            name='university',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='specialities', to='profiles.universitys'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='specialitys',
            name='name',
            field=models.CharField(default='Не указано', max_length=100),
        ),
        migrations.AlterField(
            model_name='universitys',
            name='name',
            field=models.CharField(default='Не указано', max_length=100),
        ),
        migrations.CreateModel(
            name='Busineses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_company', models.CharField(max_length=100)),
                ('inn_company', models.IntegerField()),
                ('possition', models.CharField(max_length=100)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_data', to='profiles.profiles')),
            ],
        ),
        migrations.DeleteModel(
            name='Business',
        ),
        migrations.DeleteModel(
            name='TypeUsers',
        ),
    ]
