# Generated by Django 5.0.4 on 2024-05-02 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profiles_type_specialitys_university_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='busineses',
            options={'verbose_name': 'Бизнес', 'verbose_name_plural': 'Бизнесы'},
        ),
        migrations.AlterModelOptions(
            name='profiles',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AlterModelOptions(
            name='specialitys',
            options={'verbose_name': 'Специальность', 'verbose_name_plural': 'Специальности'},
        ),
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name': 'Студент', 'verbose_name_plural': 'Студенты'},
        ),
        migrations.AlterModelOptions(
            name='universitys',
            options={'verbose_name': 'Университет', 'verbose_name_plural': 'Университеты'},
        ),
        migrations.AlterField(
            model_name='busineses',
            name='inn_company',
            field=models.IntegerField(verbose_name='ИНН компании'),
        ),
        migrations.AlterField(
            model_name='busineses',
            name='name_company',
            field=models.CharField(max_length=100, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='busineses',
            name='possition',
            field=models.CharField(max_length=100, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='busineses',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_data', to='profiles.profiles', verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='firstname',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='secondname',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='therename',
            field=models.CharField(max_length=100, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='type',
            field=models.CharField(choices=[('Студент', 'Студент'), ('Преподаватель', 'Преподаватель'), ('Бизнес', 'Бизнес')], max_length=100, verbose_name='Тип учетной записи'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='specialitys',
            name='name',
            field=models.CharField(default='Не указано', max_length=100, verbose_name='Название специальности'),
        ),
        migrations.AlterField(
            model_name='specialitys',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.universitys', verbose_name='Университет'),
        ),
        migrations.AlterField(
            model_name='students',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_data', to='profiles.profiles', verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='students',
            name='speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.specialitys', verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='students',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.universitys', verbose_name='Университет'),
        ),
        migrations.CreateModel(
            name='Departament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Не указано', max_length=100, verbose_name='Название кафедры')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.universitys', verbose_name='Университет')),
            ],
            options={
                'verbose_name': 'Кафедру',
                'verbose_name_plural': 'Кафедры',
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(choices=[(0, 'Лаборант'), (1, 'Ассистент'), (2, 'Старший преподаватель'), (3, 'Доцент'), (4, 'Профессор'), (5, 'Заведующий кафедрой')])),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.departament', verbose_name='Кафедры')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_data', to='profiles.profiles', verbose_name='Логин')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.universitys', verbose_name='Университет')),
            ],
            options={
                'verbose_name': 'Учителя',
                'verbose_name_plural': 'Учителей',
            },
        ),
    ]
