# Generated by Django 5.0.4 on 2024-05-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_busineses_options_alter_profiles_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='avatar',
            field=models.ImageField(default=None, null=True, upload_to='avatars', verbose_name='Аватар'),
        ),
    ]
