# Generated by Django 5.0.4 on 2024-05-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profiles_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='type',
            field=models.IntegerField(choices=[(0, 'Студент'), (1, 'Преподаватель'), (2, 'Бизнес')], verbose_name='Тип учетной записи'),
        ),
    ]
