# Generated by Django 5.0.4 on 2024-05-02 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0002_alter_event_options_event_name_alter_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corpuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Не указано', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Auditories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Не указано', max_length=100)),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.corpuses')),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datatime', models.DateTimeField(default='Не указано')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.auditories')),
            ],
        ),
    ]
