# Generated by Django 5.0.4 on 2024-05-02 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coworking', '0002_corpuses_auditories_delete_coworingreservations'),
        ('event', '0003_alter_connectevent_options_alter_event_name'),
        ('profiles', '0003_alter_busineses_options_alter_profiles_options_and_more'),
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditories',
            name='corpus',
        ),
        migrations.AlterField(
            model_name='reservations',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coworking.auditories', verbose_name='Аудитория'),
        ),
        migrations.AlterModelOptions(
            name='reservations',
            options={'verbose_name': 'Бронирование', 'verbose_name_plural': 'Забронировать'},
        ),
        migrations.AddField(
            model_name='reservations',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.profiles', verbose_name='Логин'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservations',
            name='datatime',
            field=models.DateTimeField(verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event', verbose_name='Мероприятие'),
        ),
        migrations.DeleteModel(
            name='Corpuses',
        ),
        migrations.DeleteModel(
            name='Auditories',
        ),
    ]
