# Generated by Django 5.0.4 on 2024-05-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='avatar_project',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='project_avatar', verbose_name='Превью проекта'),
        ),
    ]
