# Generated by Django 5.0.4 on 2024-05-03 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_busineses_options_alter_profiles_options_and_more'),
        ('projects', '0002_alter_projects_options_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='author',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile_data', to='profiles.profiles', verbose_name='Автор проекта'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projects', verbose_name='Проект')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profiles', verbose_name='Подписчик')),
            ],
            options={
                'verbose_name': 'Подписчика',
                'verbose_name_plural': 'Подписки',
            },
        ),
    ]
