# Generated by Django 5.0.4 on 2024-05-08 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_typeprojects_name_type_typeprojects_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='project_type', to='projects.typeprojects', verbose_name='Тип проекта'),
        ),
    ]
