# Generated by Django 5.0.4 on 2024-05-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projects_extra_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='extra_data',
            field=models.JSONField(default={}, verbose_name='Дополнительные данные'),
        ),
    ]
