# Generated by Django 5.0.4 on 2024-05-04 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_projects_extra_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.projects', verbose_name='Проект'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comments',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
