# Generated by Django 5.0.4 on 2024-05-04 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_comments_project_alter_comments_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время комментария'),
        ),
    ]
