# Generated by Django 5.0.4 on 2024-05-04 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_projects_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_type', models.ImageField(choices=[(0, 'Коммерческие'), (1, 'StartApp'), (2, 'Образовательные'), (3, 'Творческие')], upload_to='', verbose_name='Тип проекта')),
                ('connect_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projects', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Тип проекта',
                'verbose_name_plural': 'Типы проектов',
            },
        ),
    ]
