# Generated by Django 5.0.4 on 2024-05-04 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_typeprojects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeprojects',
            name='connect_project',
        ),
        migrations.AddField(
            model_name='typeprojects',
            name='project',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='type_project', to='projects.projects', verbose_name='Проект'),
            preserve_default=False,
        ),
    ]
