# Generated by Django 5.0.4 on 2024-05-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_remove_typeprojects_connect_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeprojects',
            name='name_type',
            field=models.IntegerField(choices=[(0, 'Коммерческие'), (1, 'StartApp'), (2, 'Образовательные'), (3, 'Творческие')], verbose_name='Тип проекта'),
        ),
    ]
