# Generated by Django 5.0.4 on 2024-05-07 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_profiles_type'),
        ('projects', '0013_alter_typeprojects_name_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='avatar_project',
            field=models.ImageField(default='', upload_to='project_avatar', verbose_name='Превью проекта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comments',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_comments', to='projects.projects', verbose_name='Проект'),
        ),
        migrations.CreateModel(
            name='Project_Subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Ожидание'), (1, 'Подтверждена'), (2, 'Отклонена')], default=1, verbose_name='Стутус регистрации')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_subscribers', to='projects.projects', verbose_name='Проект')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profiles', verbose_name='Подписчик')),
            ],
            options={
                'verbose_name': 'Подписчика',
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.DeleteModel(
            name='Subscribers',
        ),
    ]
