# Generated by Django 5.0.4 on 2024-05-07 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_projects_avatar_project_alter_comments_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeprojects',
            name='project',
        ),
    ]
