# Generated by Django 5.0.4 on 2024-05-07 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coworking', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Не указано', max_length=100, verbose_name='Название мероприятия')),
                ('type', models.IntegerField(choices=[(0, 'Академические'), (1, 'Культурные и общественные'), (2, 'Спортивные'), (3, 'Образовательные')], verbose_name='Тип мероприятия')),
                ('short_description', models.CharField(max_length=100, verbose_name='Краткое описание')),
                ('description', models.TextField(verbose_name='Описание')),
                ('avatar', models.ImageField(upload_to='avatar_event', verbose_name='Картинка мероприятия')),
                ('start_event', models.DateTimeField(verbose_name='Время проведения мероприятия')),
                ('end_event', models.DateTimeField(verbose_name='Время окончания мероприятия')),
                ('extra_data', models.JSONField(default=dict, verbose_name='Дополнительные данные')),
                ('place_event', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='coworking.auditories', verbose_name='Место проведения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profiles', verbose_name='Логин')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='ConnectEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reg', models.DateTimeField(auto_now_add=True, verbose_name='Время регистрации')),
                ('state', models.IntegerField(choices=[(0, 'Ожидание'), (1, 'Одобрено')], default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profiles')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
            ],
            options={
                'verbose_name': 'Приосединение к мероприятию',
                'verbose_name_plural': 'Присоединится к мероприятиям',
            },
        ),
        migrations.CreateModel(
            name='Event_Subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Ожидание'), (1, 'Подтверждена'), (2, 'Отклонена')], default=0, verbose_name='Стутус регистрации')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_subscribers', to='event.event', verbose_name='Проект')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.profiles', verbose_name='Подписчик')),
            ],
            options={
                'verbose_name': 'Подписчика',
                'verbose_name_plural': 'Подписки',
            },
        ),
    ]
