# Generated by Django 5.0.4 on 2024-05-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='Не указано', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('Академические', 'Академические'), ('Культурные и общественные', 'Культурные и общественные'), ('Спортивные', 'Спортивные'), ('Образовательные', 'Образовательные')], max_length=100),
        ),
    ]
