# Generated by Django 5.0.4 on 2024-05-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='avatar',
            field=models.ImageField(default=None, null=True, upload_to='avatar_event', verbose_name='Картинка мероприятия'),
        ),
    ]
