# Generated by Django 5.0.4 on 2024-05-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_event_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='avatar',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='avatar_event', verbose_name='Картинка мероприятия'),
        ),
    ]
