# Generated by Django 5.0.4 on 2024-05-02 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_event_options_event_name_alter_event_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connectevent',
            options={'verbose_name': 'Приосединение к мероприятию', 'verbose_name_plural': 'Присоединится к мероприятиям'},
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(default='Не указано', max_length=100, verbose_name='Название мероприятия'),
        ),
    ]
