# Generated by Django 5.0.4 on 2024-05-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_connectevent_options_alter_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='avatar',
            field=models.ImageField(default=1, upload_to='avatar_event', verbose_name='Картинка мероприятия'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.IntegerField(choices=[(0, 'Академические'), (1, 'Культурные и общественные'), (2, 'Спортивные'), (3, 'Образовательные')], verbose_name='Тип мероприятия'),
        ),
    ]
