# Generated by Django 5.0.4 on 2024-05-06 18:01

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coworking', '0003_remove_auditories_status_auditories_capacity'),
        ('event', '0004_event_avatar_alter_event_type'),
        ('profiles', '0005_alter_profiles_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_event',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 6, 18, 0, 59, 523061, tzinfo=datetime.timezone.utc), verbose_name='Время окончания мероприятия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='extra_data',
            field=models.JSONField(default=dict, verbose_name='Дополнительные данные'),
        ),
        migrations.AddField(
            model_name='event',
            name='place_event',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='coworking.auditories', verbose_name='Место проведения'),
        ),
        migrations.AddField(
            model_name='event',
            name='start_event',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 6, 18, 1, 8, 773273, tzinfo=datetime.timezone.utc), verbose_name='Время проведения мероприятия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.profiles', verbose_name='Логин'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='connectevent',
            name='state',
            field=models.IntegerField(choices=[(0, 'Ожидание'), (1, 'Одобрено')], default=0),
        ),
    ]
