# Generated by Django 5.0.4 on 2024-05-11 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coworking', '0001_initial'),
        ('event', '0006_alter_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Дополнительные данные'),
        ),
        migrations.AlterField(
            model_name='event',
            name='place_event',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place_event', to='coworking.auditories', verbose_name='Место проведения'),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.IntegerField(choices=[(0, 'Академические'), (1, 'Культурные и общественные'), (2, 'Спортивные'), (3, 'Образовательные')], default=1, verbose_name='Тип мероприятия'),
            preserve_default=False,
        ),
    ]
