# Generated by Django 5.0.4 on 2024-05-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_event_subscribers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='comment',
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='short_description',
            field=models.CharField(default='', max_length=100, verbose_name='Краткое описание'),
            preserve_default=False,
        ),
    ]
