# Generated by Django 5.0.4 on 2024-05-12 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_typeevents_alter_event_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='type',
            new_name='type_event',
        ),
    ]
