version: "3.9"

services: 
  django:
    container_name: django
    restart: always
    build:
      context: ./back-end # django service folder
    image: back-end
    command: python3 ./src/manage.py runserver django:8000
    volumes:
      - ./back-end/src:/app/src
      # - ./persistentdata/static:/app/src/static # <--here
      # - ./persistentdata/media:/app/src/media # <--here
    depends_on: 
      - postgresql-db
      
  postgresql-db:
    container_name: postgresql-db
    restart: always
    image: postgres
    #volumes:
      #- ./persistentdata/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "dbhac"
      POSTGRES_USER: "hacuser"
      POSTGRES_PASSWORD: "hacpass"
    env_file: ./postgresql/.env
  nginx:
    container_name: nginx
    restart: always
    build:
      context: ./nginx
    ports:
      - "8000:80" # port exposed to outside world.
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./back-end/src/static:/var/www/static
      - ./back-end/src/media:/var/www/media
    depends_on:
      - django