# Generated by Django 5.0.4 on 2024-05-02 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_alter_profiles_type_specialitys_university_and_more'),
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoworingReservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default='Не указано')),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reserv_data', to='reservation.reservations')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profiles_data', to='profiles.profiles')),
            ],
        ),
    ]
