# Generated by Django 5.0.4 on 2024-05-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coworking', '0002_corpuses_auditories_delete_coworingreservations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditories',
            name='status',
        ),
        migrations.AddField(
            model_name='auditories',
            name='capacity',
            field=models.IntegerField(default=0, verbose_name='Вместимость аудитории'),
            preserve_default=False,
        ),
    ]
